import { auth } from '@/lib/auth'
import { getAdminOffers } from '@/app/actions/offers'
import { headers } from 'next/headers'
import { redirect } from 'next/navigation'
import Link from 'next/link'
import { AdminOfferActions } from '@/components/admin-offer-actions'
import { SignOutButton } from '@/components/sign-out-button'

export const dynamic = 'force-dynamic'

export default async function AdminPage() { const session = await auth.api.getSession({ headers: await headers() }); if (!session?.user) redirect('/admin/login'); const items = await getAdminOffers(); return <main className="admin-shell"><header className="admin-topbar"><a className="brand" href="/"><span className="brand-mark">S</span><span>soleando</span></a><div className="admin-user"><span>{session.user.name || session.user.email}</span><a href="/">Ver sitio ↗</a><SignOutButton /></div></header><section className="admin-content"><div className="admin-heading"><div><p className="eyebrow">Panel de ofertas</p><h1>Tu catálogo,<br /><em>siempre listo.</em></h1><p className="muted">Crea ofertas manuales ahora. Más adelante podremos sincronizar las de Instagram sin perder tus ediciones.</p></div><Link className="button button-sun" href="/admin/ofertas/nueva">Nueva oferta ↗</Link></div><div className="admin-stats"><div><strong>{items.length}</strong><span>Total ofertas</span></div><div><strong>{items.filter((item) => item.status === 'published').length}</strong><span>Publicadas</span></div><div><strong>{items.filter((item) => item.source === 'instagram').length}</strong><span>Desde Instagram</span></div></div><div className="admin-list"><div className="admin-list-head"><span>Oferta</span><span>Origen</span><span>Estado</span></div>{items.length ? items.map((item) => <div className="admin-row" key={item.id}><div><strong>{item.title}</strong><small>{item.destination} · {item.category}</small></div><span className="source-pill">{item.source === 'instagram' ? 'Instagram' : 'Manual'}</span><span className={`status-pill status-${item.status}`}>{item.status === 'published' ? 'Publicada' : item.status === 'archived' ? 'Archivada' : 'Borrador'}</span><div className="admin-row-actions"><Link href={`/admin/ofertas/${item.id}/editar`}>Editar</Link><AdminOfferActions id={item.id} /></div></div>) : <div className="empty-state"><p>Aún no hay ofertas.</p><Link className="text-link" href="/admin/ofertas/nueva">Crea la primera oferta ↗</Link></div>}</div></section></main> }
