'use client'
import { FormEvent, useState } from 'react'
import { createOffer } from '@/app/actions/offers'
import { useRouter } from 'next/navigation'

export function OfferForm() { const router = useRouter(); const [error, setError] = useState(''); const [loading, setLoading] = useState(false)
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(''); const form = new FormData(event.currentTarget); const payload = Object.fromEntries(form.entries()); const result = await createOffer({ ...payload, featured: form.get('featured') === 'on', status: form.get('status') || 'draft' }).catch(() => null); if (!result) setError('Revisa los campos e inténtalo de nuevo.'); else { router.push('/admin'); router.refresh() } setLoading(false) }
  return <form className="offer-form" onSubmit={submit}><div className="form-grid"><label>Título<input name="title" placeholder="Isla Saona al atardecer" required /></label><label>Destino<input name="destination" placeholder="Bayahibe, República Dominicana" required /></label><label>Categoría<select name="category" defaultValue="Excursiones"><option>Excursiones</option><option>Viajes</option><option>Resorts</option><option>Cruceros</option></select></label><label>Precio<input name="price" placeholder="129" inputMode="decimal" /></label><label>Moneda<select name="currency" defaultValue="USD"><option>USD</option><option>DOP</option><option>EUR</option></select></label><label>Fecha o duración<input name="dateLabel" placeholder="Día completo · Grupos pequeños" /></label></div><label>Descripción<textarea name="description" rows={4} placeholder="Cuenta qué hace especial esta experiencia…" required /></label><label>Incluye <span className="field-hint">separa cada elemento con comas</span><input name="includes" placeholder="Transporte, almuerzo, guía local" /></label><label>URL de imagen<input name="imageUrl" type="url" placeholder="https://…" required /></label><label>Instagram (opcional)<input name="instagramUrl" type="url" placeholder="https://instagram.com/p/…" /></label><div className="form-options"><label className="checkbox"><input name="featured" type="checkbox" /> Destacar en portada</label><label>Estado<select name="status" defaultValue="draft"><option value="draft">Borrador</option><option value="published">Publicada</option></select></label></div>{error && <p className="form-error">{error}</p>}<button className="button button-sun" disabled={loading}>{loading ? 'Guardando…' : 'Guardar oferta ↗'}</button></form>
}
